server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  main:
    allow-circular-references: true

  #spring.mvc.view.prefix=.mustache
  #spring.mvc.view.suffix=/templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 83894557482-v5cbgg6jot99hrs1rl80cj55gc75dhfc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
